"""
Metadata, State, and Prompt Template

Loads configuration files that the LangGraph nodes need:
  - metadata.json          → single rich file with columns, stats, samples, forbidden entries
  - prompt_template.txt    → system prompt for SQL generation
  - State TypedDict        → data shape flowing through the graph
  - QueryOutput            → structured output format for LLM
"""

import json
from pathlib import Path
from typing_extensions import TypedDict, Annotated
from langchain_core.prompts import ChatPromptTemplate

from app.services.llm._config import config, logger


# ── Metadata ─────────────────────────────────────────────────────

def load_metadata():
    """
    Load the single rich metadata.json generated by enrich_metadata.py.

    Format:
        {
          "history2.fixtures__balls": {
            "table_summary": "...",
            "columns": {
              "score__runs": {"type": "bigint", "description": "...", "min": 0, "max": 8, "sample_values": [...]},
              "❌ NO 'score'": "Use score__runs in this table"
            },
            "sample_rows": [{...}, ...]
          }
        }
    """
    try:
        with open(config.files.METADATA_FILE, 'r', encoding='utf-8') as f:
            metadata = json.load(f)
            logger.info(f"Metadata loaded from {config.files.METADATA_FILE}")
            return metadata
    except FileNotFoundError:
        logger.error(f"Metadata file not found at {config.files.METADATA_FILE}")
        return {}
    except json.JSONDecodeError as e:
        logger.error(f"Failed to parse metadata JSON: {e}")
        return {}


# Filter out tables that are irrelevant to cricket queries.
# Exposing them causes the LLM to generate queries referencing
# tables like history2.venues or history2.continents which either
# have no useful cricket data or produce wrong joins.
_EXCLUDED_TABLES = {
    "history2.venues",
    "history2.positions",
}

_raw_metadata = load_metadata()
metadata = {k: v for k, v in _raw_metadata.items() if k not in _EXCLUDED_TABLES}


def get_flat_metadata():
    """
    Extract a flat {table: {column: description}} view for validators.
    Validators expect the old format — this adapts the new format.
    """
    flat = {}
    for table_name, table_data in metadata.items():
        cols = table_data.get("columns", table_data)
        if isinstance(cols, dict):
            flat_cols = {}
            for col_name, col_info in cols.items():
                if col_name.startswith("❌"):
                    flat_cols[col_name] = col_info
                elif isinstance(col_info, dict):
                    flat_cols[col_name] = col_info.get("description", "")
                else:
                    flat_cols[col_name] = col_info
            flat[table_name] = flat_cols
        else:
            flat[table_name] = table_data
    return flat


flat_metadata = get_flat_metadata()


# ── Data Context for Prompt ───────────────────────────────────────

def build_data_context():
    """
    Build a context string from metadata that gets injected into the prompt.
    Shows the LLM what real data looks like — sample rows + value ranges.
    """
    if not metadata:
        return ""

    lines = [
        "",
        "------------------------------------",
        "REAL DATA CONTEXT (auto-generated from database)",
        "------------------------------------",
        "Use this to understand what values actually look like in each table.",
        "",
    ]

    for table_name, table_data in metadata.items():
        lines.append(f"--- {table_name} ---")

        # Table summary
        summary = table_data.get("table_summary", "")
        if summary:
            lines.append(f"Purpose: {summary}")

        # Sample rows
        sample_rows = table_data.get("sample_rows", [])
        if sample_rows:
            lines.append("Sample row:")
            row = sample_rows[0]
            for k, v in row.items():
                lines.append(f"  {k} = {v}")

        # Column samples
        columns = table_data.get("columns", {})
        sample_lines = []
        for col_name, col_info in columns.items():
            if col_name.startswith("❌"):
                continue
            if isinstance(col_info, dict) and "sample_values" in col_info:
                samples = col_info["sample_values"]
                if samples:
                    sample_lines.append(f"  {col_name}: e.g. {', '.join(samples)}")
        if sample_lines:
            lines.append("Column samples:")
            lines.extend(sample_lines)

        lines.append("")

    # NOTE: Cricket domain rules (wickets semantics, column disambiguation,
    # join dangers) live in cricket_knowledge.txt — not duplicated here.
    lines.extend([
        "------------------------------------",
        "",
    ])

    return "\n".join(lines)


data_context = build_data_context()


# ── Value Ranges (used by sanity checker) ─────────────────────────

sanity_ranges = {}


# ── State TypedDict ──────────────────────────────────────────────

class State(TypedDict):
    """Data shape that flows through the LangGraph pipeline."""
    question: str
    query: str
    result: str
    answer: str
    table_info: dict
    dialect: str
    metadata: dict
    din_context: str
    query_warnings: list


# ── Prompt Template ──────────────────────────────────────────────

def load_cricket_knowledge():
    """Load cricket domain knowledge file."""
    try:
        with open(config.files.CRICKET_KNOWLEDGE_FILE, 'r', encoding='utf-8') as f:
            knowledge = f.read()
            logger.info(f"Cricket knowledge loaded from {config.files.CRICKET_KNOWLEDGE_FILE}")
            return knowledge
    except FileNotFoundError:
        logger.warning(f"Cricket knowledge file not found at {config.files.CRICKET_KNOWLEDGE_FILE}")
        return ""
    except Exception as e:
        logger.error(f"Failed to load cricket knowledge: {e}")
        return ""


cricket_knowledge = load_cricket_knowledge()


# ── Cricket Knowledge Summary (for answer generation & question gen) ──

CRICKET_ANSWER_CONTEXT = """Cricket stats context for interpreting results:
- Strike Rate ~100 is par, >150 is aggressive, >200 is explosive
- Economy Rate ~6-7 is good in T20, >10 is expensive
- Run Rate ~8-9 is par in T20, >10 is above average
- Batting Average >30 is good, >50 is elite
- Dot Ball % ~30-40% is typical in T20, >40% is good bowling, <20% is poor (batsmen scoring freely)
- "Wickets in hand" = 10 minus wickets lost
- Powerplay = overs 1-6, Middle = 7-15, Death = 16-20
- T20 max PER SINGLE MATCH: ~300 runs, 20 overs, 10 wickets per innings
- When results aggregate across MULTIPLE matches, limits scale accordingly (e.g., 5 matches can have up to 50 total wickets, 1500 total runs, etc.). Do NOT flag aggregated multi-match totals as unrealistic by comparing them to single-match limits.
- Career total runs CAN be in the thousands — do NOT flag high career totals as unreliable
- Successful chase = chasing team's score > first innings score
- IMPORTANT: Only flag a result as unrealistic if it is truly impossible given the number of matches/innings involved. Report the SQL results factually without second-guessing valid data."""


CRICKET_QUESTION_CONTEXT = """Available cricket data (use this to frame answerable questions):
- Ball-by-ball data: every delivery with batsman, bowler, runs, wickets
- Batting stats: score, strike rate, balls faced per batsman
- Bowling stats: wickets taken, runs conceded, economy per bowler
- Innings totals: team score, wickets lost, overs played
- Match identification via fixture_id

NOT available (do NOT ask about):
- Dates, years, seasons, or time periods
- Venues, grounds, stadiums, or locations
- Weather, toss, or pitch conditions
- Partnerships or partnership runs
- Player ages or career spans

Key facts:
- Player names are in fixtures__balls (batsman__fullname, bowler__fullname)
- Teams identified by team__name, NOT team_id (which is numeric)
- "Wickets" in innings totals means wickets LOST, not in hand
- Chase/batting second = inning 2, scoreboard S2"""


def load_prompt_template():
    """
    Load SQL generation prompt and combine with:
      1. Cricket domain knowledge (ball format, metrics, chase logic)
      2. Real data context (sample rows, column samples)
      3. Table schema (injected by LangChain at runtime)
    """
    try:
        with open(config.files.PROMPT_TEMPLATE_FILE, 'r', encoding='utf-8') as f:
            template = f.read()
            logger.info(f"Prompt template loaded from {config.files.PROMPT_TEMPLATE_FILE}")
    except FileNotFoundError:
        logger.error(f"Prompt template file not found at {config.files.PROMPT_TEMPLATE_FILE}")
        template = "You are a SQL query generator for cricket statistics."
    except Exception as e:
        logger.error(f"Failed to load prompt template: {e}")
        template = "You are a SQL query generator for cricket statistics."

    # Inject cricket knowledge at the top (after the first line)
    if cricket_knowledge:
        first_newline = template.find("\n")
        if first_newline > 0:
            template = template[:first_newline + 1] + "\n" + cricket_knowledge + "\n" + template[first_newline + 1:]
        else:
            template = cricket_knowledge + "\n" + template

    # Inject data context before the TABLE SCHEMA section
    if data_context and "TABLE SCHEMA:" in template:
        template = template.replace("TABLE SCHEMA:", data_context + "\nTABLE SCHEMA:")
    elif data_context:
        template += "\n" + data_context

    return template


custom_message = load_prompt_template()

query_prompt_template = ChatPromptTemplate.from_messages([
    ("system", custom_message),
    ("human", "{input}")
])

logger.info(f"Template variables: {query_prompt_template.input_variables}")


# ── QueryOutput ──────────────────────────────────────────────────

class QueryOutput(TypedDict):
    """Structured output format for LLM SQL generation."""
    query: Annotated[str, ..., "Syntactically valid SQL query."]
